---
version: "3"
services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    profiles:
      - db
      - all
    ports:
      - '5435:5432'

  travel-talk-server:
    image: ghcr.io/traveltransporttalk/travel-talk-server:latest
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
    depends_on:
      - postgres
    profiles:
      - all
    ports:
      - "8080:8080"

  registration-bot:
    image: ghcr.io/traveltransporttalk/register-bot:latest
    depends_on:
      - travel-talk-server
    environment:
      - 'API=http://travel-talk-server:8080/tt/users'
      - 'BOT_TOKEN=<YOUR_TOKEN>'
    profiles:
      - all

  webui:
    image: ghcr.io/traveltransporttalk/traveltalk:latest
    environment:
      - "API_BASE_URL=http://travel-talk-server:8080/tt/"
    depends_on:
      - travel-talk-server
    ports:
      - "8501:8501"
    profiles:
      - all
